name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email LinXunFeng
          git config --global user.name linxunfeng@yeah.net
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/fluttercandies/flutter_scrollview_observer.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f